FROM ruby:4.0.3

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y postgresql-client

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "bundle exec rake db:create && bundle exec rake db:migrate && rm -f ./tmp/pids/server.pid && exec bundle exec rails server -b 0.0.0.0"]

# sudo chown -R $(id -u):$(id -g) .
